USE [master]
GO

/****** Object:  Database [NodoTIC]    Script Date: 19/09/2023 7:50:23 a. m. ******/
CREATE DATABASE [NodoTIC]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'NodoTIC', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NodoTIC.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'NodoTIC_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\NodoTIC_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [NodoTIC].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [NodoTIC] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [NodoTIC] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [NodoTIC] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [NodoTIC] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [NodoTIC] SET ARITHABORT OFF 
GO

ALTER DATABASE [NodoTIC] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [NodoTIC] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [NodoTIC] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [NodoTIC] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [NodoTIC] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [NodoTIC] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [NodoTIC] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [NodoTIC] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [NodoTIC] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [NodoTIC] SET  ENABLE_BROKER 
GO

ALTER DATABASE [NodoTIC] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [NodoTIC] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [NodoTIC] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [NodoTIC] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [NodoTIC] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [NodoTIC] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [NodoTIC] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [NodoTIC] SET RECOVERY FULL 
GO

ALTER DATABASE [NodoTIC] SET  MULTI_USER 
GO

ALTER DATABASE [NodoTIC] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [NodoTIC] SET DB_CHAINING OFF 
GO

ALTER DATABASE [NodoTIC] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [NodoTIC] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [NodoTIC] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [NodoTIC] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [NodoTIC] SET QUERY_STORE = ON
GO

ALTER DATABASE [NodoTIC] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [NodoTIC] SET  READ_WRITE 
GO

USE [NodoTIC]
GO
CREATE TABLE [dbo].[clientes](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[nombres] [varchar](350) NULL,
	[apellidos] [varchar](350) NULL,
	[ciudad] [varchar](250) NULL,
	[telefono] [varchar](80) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO